tweaked size-limit with better kpi (#35)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,7 +35,9 @@ jobs:
           node-version: '15'
 
       # TODO(fuxingloh): reg net testing
-      - run: echo "::error::not yet implemented"
+      - run: |
+          echo "::error::not yet implemented"
+          exit 1
 
   test-net:
     name: TestNet
@@ -48,7 +50,9 @@ jobs:
           node-version: '15'
 
       # TODO(fuxingloh): test net testing
-      - run: echo "::error::not yet implemented"
+      - run: |
+          echo "::error::not yet implemented"
+          exit 1
 
   main-net:
     name: MainNet
@@ -61,4 +65,6 @@ jobs:
           node-version: '15'
 
       # TODO(fuxingloh): main net testing?
-      - run: echo "::error::not yet implemented"
+      - run: |
+          echo "::error::not yet implemented"
+          exit 1
